PR template: move description section to top, remove heading
foxglove/.github pull request #8
Opened 2024-05-21 04:11 UTC by james-rms

### Changelog

### Docs

### Description

Problem: When I have finished a patch set and want to create a PR, my desire is to open the link and start typing my reasoning immediately. However, I find the prompt to fill out entries for changelog and docs first distracting.

Solution: remove the "Description" heading and move the description section to the top. When the page is opened, the cursor appears in the description area, and it's seamless to start typing.

Also, if a PR consists of one commit with a message, that message will automatically appear where it should in the PR description.

<table><tr><th>Before</th><th>After</th></tr><tr><td>

</td><td>

</td></tr></table>

2024-05-21 04:23 UTC, jtbandes commented
IMO from a reader standpoint it is nicer to have the short summary (changelog) prior to the detailed description, and I believe we should optimize for the readers because PRs are read more often than they are written.

2024-05-21 13:41 UTC, sofuture commented
I'm 👍 on this change. Changelogs and docs do not always apply (of course I realize I'm coming with a bias towards the type of changes I make!), and it feels odd to start a PR with 2 blank sections instead of an overview of the change. I think this change also helps readability.

My natural inclination for writing a PR is:

- here's what changed
- expound on details, as applicable
- further background and justification, as applicable
- things that need noted (changelog, blockers, todos, deploy, complications)

2024-05-21 13:41 UTC, sofuture approved these changes

2024-05-21 14:44 UTC, defunctzombie commented
> Problem: When I have finished a patch set and want to create a PR, my desire is to open the link and start typing my reasoning immediately. However, I find the prompt to fill out entries for changelog and docs first distracting.

This is because the first part of the entry is not for you - it is to make it easier to create our public-facing changelog and docs updates for the folks responsible for putting together releases. If you want to write those last you can do so and skip right to the description section.

2024-05-21 14:45 UTC, defunctzombie requested changes
Waiting for @banisadr to weigh in because this ordering is designed to make you think conscientiously about those sections by putting them first.

2024-05-21 14:46 UTC, defunctzombie commented
> I'm 👍 on this change. Changelogs and docs do not always apply (of course I realize I'm coming with a bias towards the type of changes I make!),

We can override this template for the repos like infra and infra admin where there's no need for these sections by adding a template file to the repo. Lets take that approach for repos we know are internal.

2024-05-22 22:30 UTC, banisadr commented
I'm aligned with @jtbandes and @defunctzombie on this - a short summary at the top is better for readers and more people read the PR description than write it. There's value in forcing ourselves to be a bit more intentional in what we write in the changelog/summary. Certainly it also makes my life easier when I scan through all of the updates to author the changelog.

My preference is if this is a pain for specific repos we update the template for those ones where change log & docs aren't commonly relevant.

2024-05-22 22:58 UTC, closed without merging